const FETCH_REQUEST = 'films/FETCH_REQUEST';
const FETCH_ERROR = 'films/FETCH_ERROR';
const FETCH_SUCCESS = 'films/FETCH_SUCCESS';
const UPLOAD_ALL_FILMS = 'films/UPLOAD_ALL_FILMS';
const REMOVE_FILM = 'films/REMOVE_FILM';
const ADD_FILM = 'films/ADD_FILM';
const SET_ACTIVE_FILM = 'films/SET_ACTIVE_FILM';
const REMOVE_ACTIVE_FILM = 'films/REMOVE_ACTIVE_FILM';

export default {
  FETCH_REQUEST,
  FETCH_ERROR,
  FETCH_SUCCESS,
  UPLOAD_ALL_FILMS,
  REMOVE_FILM,
  ADD_FILM,
  SET_ACTIVE_FILM,
  REMOVE_ACTIVE_FILM,
};
